import { useState } from 'react';
import { lenders, Lender } from '@/data/lenders';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { Download, X, Building2, TrendingUp, Percent, Calendar, Award } from 'lucide-react';

interface ProvisionalSanctionLetterProps {
  onClose: () => void;
  onApplyNow: (lender: Lender) => void;
}

export const ProvisionalSanctionLetter = ({ onClose, onApplyNow }: ProvisionalSanctionLetterProps) => {
  const today = new Date();
  const formattedDate = today.toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const referenceId = `HPR/PSL/${today.getFullYear().toString().slice(-2)}${(today.getMonth() + 1).toString().padStart(2, '0')}${today.getDate().toString().padStart(2, '0')}/${Math.floor(1000 + Math.random() * 9000)}`;

  // Sort lenders by approval probability (highest first)
  const rankedLenders = [...lenders].sort((a, b) => b.approvalProbability - a.approvalProbability);

  const getApprovalColor = (probability: number) => {
    if (probability >= 90) return 'text-approval';
    if (probability >= 80) return 'text-trust';
    return 'text-warning';
  };

  return (
    <div className="animate-fade-in">
      {/* Header */}
      <div className="flex items-start justify-between mb-8">
        <div>
          <h1 className="font-display text-2xl md:text-3xl font-bold italic text-navy mb-1">
            PROVISIONAL SANCTION LETTER
          </h1>
          <p className="text-muted-foreground text-sm">Generated by Happirate AI Smart Lending Engine</p>
        </div>
        <div className="flex items-center gap-3">
          <Button className="gradient-primary hover:opacity-90">
            <Download className="w-4 h-4 mr-2" />
            Download PSL
          </Button>
          <button
            onClick={onClose}
            className="p-2 hover:bg-secondary rounded-lg transition-colors"
          >
            <X className="w-5 h-5 text-muted-foreground" />
          </button>
        </div>
      </div>

      <div className="border-t border-border pt-8">
        {/* Application Snapshot */}
        <div className="card-elevated p-6 mb-8">
          <h2 className="font-display text-lg font-semibold text-trust mb-4 italic">
            Application Snapshot
          </h2>
          <div className="grid md:grid-cols-2 gap-4">
            <div className="flex justify-between py-2 border-b border-border">
              <span className="text-muted-foreground">Date of Issuance:</span>
              <span className="font-semibold">{formattedDate}</span>
            </div>
            <div className="flex justify-between py-2 border-b border-border">
              <span className="text-muted-foreground">Reference ID:</span>
              <span className="font-semibold text-navy">{referenceId}</span>
            </div>
            <div className="flex justify-between py-2 border-b border-border">
              <span className="text-muted-foreground">Borrower Name:</span>
              <span className="font-semibold">Maya Reddy</span>
            </div>
            <div className="flex justify-between py-2 border-b border-border">
              <span className="text-muted-foreground">Requested Loan:</span>
              <span className="font-semibold">Personal</span>
            </div>
            <div className="flex justify-between py-2 border-b border-border">
              <span className="text-muted-foreground">Profile Score:</span>
              <span className="font-semibold text-approval">Excellent (CIBIL: 785)</span>
            </div>
            <div className="flex justify-between py-2 border-b border-border">
              <span className="text-muted-foreground">Amount & Tenure:</span>
              <span className="font-semibold">₹ 12,345 for 5 Years</span>
            </div>
          </div>
        </div>

        {/* Section A: Eligible & Sanctioned Offers */}
        <div className="mb-8">
          <h2 className="font-display text-xl md:text-2xl font-bold text-navy mb-2">
            SECTION A: ELIGIBLE & SANCTIONED OFFERS
          </h2>
          <p className="text-muted-foreground mb-6">
            Based on the assessment of your current credit profile and verified income, we identified the following top loan offers:
          </p>

          <div className="space-y-4">
            {rankedLenders.map((lender, index) => (
              <div
                key={lender.id}
                className={cn(
                  'card-elevated p-5 transition-all',
                  index === 0 && 'ring-2 ring-approval'
                )}
              >
                {index === 0 && (
                  <div className="inline-flex items-center gap-1.5 bg-approval text-white px-3 py-1 rounded-full text-xs font-semibold mb-3">
                    <Award className="w-3.5 h-3.5" />
                    Best Match
                  </div>
                )}

                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                  {/* Lender Info */}
                  <div className="flex items-center gap-4">
                    <div className={cn(
                      'w-12 h-12 rounded-xl flex items-center justify-center font-bold text-sm',
                      'bg-secondary text-navy'
                    )}>
                      <Building2 className="w-6 h-6" />
                    </div>
                    <div>
                      <div className="text-xs text-muted-foreground mb-0.5">RANK {index + 1}</div>
                      <h3 className="font-display font-bold text-lg">{lender.name}</h3>
                      <p className="text-sm text-muted-foreground">
                        {lender.type === 'Bank' ? 'Personal Loan' : 'Premium Personal Loan'}
                      </p>
                    </div>
                  </div>

                  {/* Approval Confidence */}
                  <div className="text-right">
                    <div className="text-xs text-muted-foreground mb-0.5">Approval Confidence</div>
                    <div className={cn('text-2xl font-bold', getApprovalColor(lender.approvalProbability))}>
                      {lender.approvalProbability}%
                    </div>
                  </div>
                </div>

                {/* Metrics */}
                <div className="grid grid-cols-3 gap-4 mt-4 pt-4 border-t border-border">
                  <div className="text-center">
                    <div className="flex items-center justify-center gap-1.5 text-muted-foreground text-xs mb-1">
                      <TrendingUp className="w-3.5 h-3.5" />
                      Max Sanction
                    </div>
                    <div className="font-bold text-lg">
                      ₹ {(lender.maxSanctionAmount / 100).toLocaleString('en-IN')}
                    </div>
                  </div>
                  <div className="text-center border-x border-border">
                    <div className="flex items-center justify-center gap-1.5 text-muted-foreground text-xs mb-1">
                      <Percent className="w-3.5 h-3.5" />
                      True APR
                    </div>
                    <div className="font-bold text-lg">{lender.trueAPR}%</div>
                  </div>
                  <div className="text-center">
                    <div className="flex items-center justify-center gap-1.5 text-muted-foreground text-xs mb-1">
                      <Calendar className="w-3.5 h-3.5" />
                      Tenure
                    </div>
                    <div className="font-bold text-lg">{lender.tenureOptions}</div>
                  </div>
                </div>

                {/* Apply Now Button */}
                <div className="mt-4 pt-4 border-t border-border flex justify-end">
                  <Button
                    onClick={() => onApplyNow(lender)}
                    className="gradient-primary hover:opacity-90"
                  >
                    Apply Now
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Close Letter Button */}
        <div className="text-center py-6 border-t border-border">
          <Button variant="ghost" onClick={onClose} className="text-muted-foreground">
            Close Letter
          </Button>
        </div>
      </div>
    </div>
  );
};
