import { lenders, Lender } from '@/data/lenders';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { Download, X, TrendingUp, Percent, Calendar, Award, Clock, CreditCard, AlertCircle, Check, CheckCircle } from 'lucide-react';

interface ProvisionalOfferLetterProps {
  onClose: () => void;
  onApplyNow: (lender: Lender) => void;
}

export const ProvisionalOfferLetter = ({ onClose, onApplyNow }: ProvisionalOfferLetterProps) => {
  const today = new Date();
  const formattedDate = today.toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });

  const referenceId = `HPR/POL/${today.getFullYear().toString().slice(-2)}${(today.getMonth() + 1).toString().padStart(2, '0')}${today.getDate().toString().padStart(2, '0')}/${Math.floor(1000 + Math.random() * 9000)}`;

  // Sort lenders by approval probability (highest first)
  const rankedLenders = [...lenders].sort((a, b) => b.approvalProbability - a.approvalProbability);

  const getApprovalColor = (probability: number) => {
    if (probability >= 90) return 'text-approval';
    if (probability >= 80) return 'text-trust';
    return 'text-warning';
  };

  return (
    <div className="animate-fade-in">
      {/* Header */}
      <div className="flex items-start justify-between mb-4">
        <div>
          <h1 className="font-display text-xl md:text-2xl font-bold italic text-navy mb-0.5">
            PROVISIONAL OFFER LETTER
          </h1>
          <p className="text-muted-foreground text-xs">Generated by Happirate AI Smart Lending Engine</p>
        </div>
        <div className="flex items-center gap-2">
          <Button className="gradient-primary hover:opacity-90" size="sm">
            <Download className="w-3.5 h-3.5 mr-1.5" />
            Download All
          </Button>
          <button
            onClick={onClose}
            className="p-1.5 hover:bg-secondary rounded-lg transition-colors"
          >
            <X className="w-4 h-4 text-muted-foreground" />
          </button>
        </div>
      </div>

      <div className="border-t border-border pt-4">
        {/* Application Snapshot - Compact */}
        <div className="card-elevated p-3 mb-4">
          <h2 className="font-display text-sm font-semibold text-trust mb-2 italic">
            Application Snapshot
          </h2>
          <div className="grid grid-cols-3 md:grid-cols-6 gap-2 text-xs">
            <div className="flex flex-col">
              <span className="text-muted-foreground">Date</span>
              <span className="font-semibold">{formattedDate}</span>
            </div>
            <div className="flex flex-col">
              <span className="text-muted-foreground">Ref ID</span>
              <span className="font-semibold text-navy truncate">{referenceId}</span>
            </div>
            <div className="flex flex-col">
              <span className="text-muted-foreground">Borrower</span>
              <span className="font-semibold">Maya Reddy</span>
            </div>
            <div className="flex flex-col">
              <span className="text-muted-foreground">Loan Type</span>
              <span className="font-semibold">Personal</span>
            </div>
            <div className="flex flex-col">
              <span className="text-muted-foreground">CIBIL</span>
              <span className="font-semibold text-approval">785</span>
            </div>
            <div className="flex flex-col">
              <span className="text-muted-foreground">Requested</span>
              <span className="font-semibold">₹12,345 / 5Y</span>
            </div>
          </div>
        </div>

        {/* Eligible Offers */}
        <div className="mb-4">
          <h2 className="font-display text-base font-bold text-navy mb-1">
            ELIGIBLE OFFERS ({rankedLenders.length})
          </h2>
          <p className="text-muted-foreground text-xs mb-3">
            Ranked by approval probability based on your profile
          </p>

          <div className="space-y-2">
            {rankedLenders.map((lender, index) => (
              <div
                key={lender.id}
                className={cn(
                  'card-elevated p-3 transition-all relative',
                  index === 0 && 'ring-2 ring-approval'
                )}
              >
                {index === 0 && (
                  <div className="absolute -top-2 left-3 inline-flex items-center gap-1 bg-approval text-white px-2 py-0.5 rounded-full text-[10px] font-semibold">
                    <Award className="w-2.5 h-2.5" />
                    Best Match
                  </div>
                )}

                <div className="flex flex-col lg:flex-row gap-3">
                  {/* Lender Info */}
                  <div className="flex items-center gap-2 lg:w-40 flex-shrink-0">
                    <div className={cn(
                      'w-8 h-8 rounded-lg flex items-center justify-center font-bold text-[10px]',
                      lender.type === 'Bank' ? 'bg-navy text-primary-foreground' : 'bg-trust text-primary-foreground'
                    )}>
                      {lender.logo.slice(0, 3)}
                    </div>
                    <div className="min-w-0">
                      <div className="text-[10px] text-muted-foreground">#{index + 1}</div>
                      <h3 className="font-display font-bold text-xs truncate">{lender.name}</h3>
                      <span className={cn(
                        'text-[10px] px-1 py-0.5 rounded',
                        lender.type === 'Bank' ? 'bg-navy/10 text-navy' : 'bg-trust/10 text-trust'
                      )}>
                        {lender.type}
                      </span>
                    </div>
                  </div>

                  {/* Key Metrics */}
                  <div className="flex-1 grid grid-cols-4 md:grid-cols-7 gap-2 text-xs">
                    <div className="flex flex-col">
                      <span className="text-muted-foreground text-[10px] flex items-center gap-0.5">
                        <CreditCard className="w-2.5 h-2.5" /> Sanction
                      </span>
                      <span className="font-bold text-xs">Up to ₹{(lender.maxSanctionAmount / 100000).toFixed(0)}L</span>
                    </div>
                    <div className="flex flex-col">
                      <span className="text-muted-foreground text-[10px] flex items-center gap-0.5">
                        <Percent className="w-2.5 h-2.5" /> APR
                      </span>
                      <span className="font-bold text-xs">{lender.trueAPR}–{lender.trueAPRMax}%</span>
                    </div>
                    <div className="flex flex-col">
                      <span className="text-muted-foreground text-[10px] flex items-center gap-0.5">
                        <Calendar className="w-2.5 h-2.5" /> Tenure
                      </span>
                      <span className="font-bold text-xs">{lender.tenureOptions}</span>
                    </div>
                    <div className="flex flex-col">
                      <span className="text-muted-foreground text-[10px] flex items-center gap-0.5">
                        <AlertCircle className="w-2.5 h-2.5" /> Proc. Fee
                      </span>
                      <span className="font-bold text-xs">{lender.processingFeeMin}–{lender.processingFeeMax}%</span>
                    </div>
                    <div className="flex flex-col">
                      <span className="text-muted-foreground text-[10px] flex items-center gap-0.5">
                        <TrendingUp className="w-2.5 h-2.5" /> Approval
                      </span>
                      <span className={cn('font-bold text-xs', getApprovalColor(lender.approvalProbability))}>
                        {lender.approvalProbability}%
                      </span>
                    </div>
                    <div className="flex flex-col">
                      <span className="text-muted-foreground text-[10px] flex items-center gap-0.5">
                        <Clock className="w-2.5 h-2.5" /> Disbursal
                      </span>
                      <span className="font-bold text-xs">{lender.disbursalTime}</span>
                    </div>
                    <div className="flex flex-col">
                      <span className="text-muted-foreground text-[10px]">Prepay</span>
                      <span className="font-medium text-[10px] truncate">{lender.prepaymentCharges}</span>
                    </div>
                  </div>

                  {/* Apply Button */}
                  <div className="flex items-center lg:w-24 flex-shrink-0">
                    <Button
                      onClick={() => onApplyNow(lender)}
                      className="gradient-primary hover:opacity-90 w-full text-xs h-8"
                      size="sm"
                    >
                      Apply Now
                    </Button>
                  </div>
                </div>

                {/* Pros, Cons, Advantages - Compact */}
                <div className="mt-2 pt-2 border-t border-border grid grid-cols-3 gap-2 text-[10px]">
                  <div>
                    <span className="font-semibold text-approval flex items-center gap-0.5 mb-0.5">
                      <CheckCircle className="w-2.5 h-2.5" /> Pros
                    </span>
                    <ul className="text-muted-foreground space-y-0.5">
                      {lender.pros.slice(0, 2).map((pro, i) => (
                        <li key={i} className="flex items-start gap-0.5 leading-tight">
                          <Check className="w-2.5 h-2.5 text-approval flex-shrink-0 mt-0.5" />
                          <span className="line-clamp-1">{pro}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <span className="font-semibold text-warning flex items-center gap-0.5 mb-0.5">
                      <AlertCircle className="w-2.5 h-2.5" /> Cons
                    </span>
                    <ul className="text-muted-foreground space-y-0.5">
                      {lender.cons.slice(0, 2).map((con, i) => (
                        <li key={i} className="flex items-start gap-0.5 leading-tight">
                          <X className="w-2.5 h-2.5 text-warning flex-shrink-0 mt-0.5" />
                          <span className="line-clamp-1">{con}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <span className="font-semibold text-trust flex items-center gap-0.5 mb-0.5">
                      <Award className="w-2.5 h-2.5" /> Unique
                    </span>
                    <ul className="text-muted-foreground space-y-0.5">
                      {lender.uniqueAdvantages.slice(0, 2).map((adv, i) => (
                        <li key={i} className="flex items-start gap-0.5 leading-tight">
                          <Award className="w-2.5 h-2.5 text-trust flex-shrink-0 mt-0.5" />
                          <span className="line-clamp-1">{adv}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Close Button */}
        <div className="text-center py-3 border-t border-border">
          <Button variant="ghost" onClick={onClose} className="text-muted-foreground text-sm">
            Close Letter
          </Button>
        </div>
      </div>
    </div>
  );
};
